### ISSUE TITLE
'  Unrecognized option "user_manager" under "fos_user"  '

### ISSUE THREAD

**Issue by bridges23** [FriendsOfSymfony/propel1-user-bundle#1]
I am getting the following message after installing the bundle:

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "user_manager" under "fos_user"

**Comment by janmarthedal** [comment]
Pull request #2 resolves this issue

**Comment by XWB** [comment]
Should be fixed in https://github.com/FriendsOfSymfony/propel1-user-bundle/pull/2
